version: '3'

services:

  server:
        build: /home/server/
        command: python ./serv.py
        ports:
          - 8080:8080
  curl:
          image: curlimages/curl
          command: http://server:8080
          depends_on:
                  - server
